### ISSUE TITLE
Generic ctor

### ISSUE THREAD

**Issue by martinus** [anthonywilliams/object_ptr#1]
Hi, I had a look at your implementation, and really like it! One suggestion though: how about instead of

```
constexpr object_ptr(std::shared_ptr<T> const &ptr_) noexcept :
	ptr(ptr_.get()) {}
constexpr object_ptr(std::unique_ptr<T> const &ptr_) noexcept :
	ptr(ptr_.get()) {}

template <
	typename U,
	typename= std::enable_if_t<std::is_convertible<U *, T *>::value>>
constexpr object_ptr(object_ptr<U> const &other) : ptr(other.get()) {}
```

You just write

```
template <typename U, typename = std::enable_if_t<std::is_convertible<decltype(U{}.get()), T*>::value>>
constexpr object_ptr(U const& other) noexcept
	: ptr(other.get()) {}
```

This has a few advantages:
* It also works for `std::unique_ptr`, `std::shared_ptr`, `std::auto_ptr`
* You can discard the `<memory>` include
* It also works for e.g. `boost::shared_ptr`, `boost::scoped_ptr`, `boost::intrusive_ptr` without the need to include any boost header in your `object_ptr.hpp`

**Comment by anthonywilliams** [comment]
Yes, I thought about adding such a constructor. However, I decided to leave it for now as I wanted to think about the constraint. "Has a member `get()` that returns a type convertible to `T*`" is a necessary part of that, but I think we probably need more (e.g. `U` provides `operator*` and `operator->`) to avoid accidental conversions (e.g. `std::future<T*>` has a member function `get()` that returns a `T*`, but I wouldn't want that to implicitly convert to `object_ptr<T>`).

**Comment by martinus** [comment]
Ah, I see. Maybe `element_type` could be used instead, at least all the boost pointers and std pointers have this type:

```
template <typename U, typename = std::enable_if_t<std::is_convertible<U::element_type*, T*>::value>>
```

**Comment by anthonywilliams** [comment]
Generic constructor added
