### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by brenoguim** [anthonywilliams/object_ptr#2]
Hi there!

A while ago I considered that this type of abstraction on my work, but it turns out they don't optimize as well as raw pointers. I tested with your library and seems to suffer from the same issue I saw back then:

https://godbolt.org/z/GUP0UU

Seems that the compiler cannot see that it's fine to call memmove/memcpy when relocating the vector in this case because the class is non-trivial.

Is it a big deal? For me it is, in some places of my code. In most places it really probably doesn't matter. But now that I know... It's kind of death by a thousand of paper cuts.

Point being, have you noticed this? Is this a concern for you at all? I just thought of bringing it up :)

**Comment by brenoguim** [comment]
By the way, it seems that it would be ok for the standard library to memcpy/memmove if type is trivially copyable and trivially movable, but today it required the type to be actually trivial.

So in the parts I really wanted to use this type of functionality, I created a "make_object_ptr" friend function and removed all constructors so the class becomes trivial.

https://godbolt.org/z/aWx5XE

Annoying as hell, but performant...

**Comment by anthonywilliams** [comment]
You are right that the compiler doesn't use `memmove` and `memcpy`, but I'm not sure that the generated assembly is any worse; it looks like a basic inlining of `memcpy` to me. Have you timed it?

**Comment by brenoguim** [comment]
`memmove` and `memcpy` can be specialized to the CPU they are running. That also makes it specially hard to reliably time it. The inline version can be faster in one cpu but not in others...

I wrote a benchmark to show that it can be slower (not that necessarely is always):
http://quick-bench.com/V_R2nU5ZiXQbUWrgoexiWzsgQFY

But really, that's a flimsy benchmark. I don't know in which architecture it's running. In practice could be better, could be worse...

**Comment by anthonywilliams** [comment]
Yes, it looks like compilers can be less good at optimizing `object_ptr<T>` vs a completely trivial variant. I think the extras are worth it; hopefully compilers will get better if more people use it.
