### ISSUE TITLE
object_ptr does not SFINAE

### ISSUE THREAD

**Issue by wgml** [anthonywilliams/object_ptr#3]
Consider following example:

```
#include "object_ptr.hpp"

struct A{};

void f(jss::object_ptr<int>);

int main()
{
    f(A{});
}
```
Example: https://wandbox.org/permlink/hWuM9JYaaGfglRlD

Expected would be an error that `A` cannot be converted to the `pointer<int>`. However, lengthy error related to missing operators is produced, suggesting the SFINAE is not working correctly.
Possible reason is that `has_smart_pointer_ops` tests depend on the class template parameters only, thus instantiating always.
Changing the tests in a following manner makes it behave as expected:
```
template<typename T>
static false_test test_op_star(...);
template<typename T>
static true_test<decltype(*std::declval<T const &>())>
test_op_star(T *);
```
Example: https://wandbox.org/permlink/I8nfk0a4QoZK8rEu

**Comment by anthonywilliams** [comment]
Yes, I spotted that a few days ago. Thanks for reminding me. Fixed.
