### ISSUE TITLE
Use specialised std::less<T*>?

### ISSUE THREAD

**Issue by wgml** [anthonywilliams/object_ptr#4]
Is there a reason to use `std::less<void>`? I believe, at least for c++14+, there is none.

https://github.com/anthonywilliams/object_ptr/blob/425967f96f1cdd2645f4cf9d55a0ddc7d5de120d/object_ptr.hpp#L170

**Comment by anthonywilliams** [comment]
C++17 still says that pointers to different objects that are not members of the same array cannot be usefully compared with `operator<`: "neither pointer compares greater than the other" ([expr.rel]p3/3).

By using `std::less` here, we ensure a single total order for all pointers, which allows `object_ptr` to be used as a key for associative containers.

**Comment by wgml** [comment]
Yes, but instead of `std::less<void>` the implementation should use `std::less<T*>`.

**Comment by anthonywilliams** [comment]
I disagree. You should use `std::less<void>` pretty much everywhere. It still provides the STO for pointers.
